version: '3.8'

services:
  db:
    image: mariadb:lts-noble
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: my-mariadb-root-password
    volumes:
      - db_data:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - docker_net

  kafka:
    image: bitnami/kafka:3.9.0
    container_name: kafka
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093

      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      # 메모리 제한을 200MB로 설정
      - KAFKA_CFG_HEAP_OPTS="-Xmx512M -Xms512M"  # 최대 및 최소 힙 메모리 크기 512MB로 설정
      - KAFKA_CFG_NUM_PARTITIONS=1  # 토픽에 대해 기본적으로 생성되는 파티션의 수: 1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false # 자동 토픽 생성 막기
      - KAFKA_CFG_LOG_RETENTION_MS=60000  # 1분 동안 로그 보관 (60,000ms)
      - KAFKA_CFG_LOG_RETENTION_BYTES=20971520  # 최대 20MB 로그만 보관
      - KAFKA_CFG_LOG_SEGMENT_BYTES=10485760  # 로그 세그먼트 크기 10MB
      - KAFKA_CFG_LOG_FLUSH_INTERVAL_MS=5000  # 5초마다 디스크에 기록
      - KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES=10000  # 10,000개의 메시지마다 디스크에 기록
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete  # 기본적으로 오래된 메시지를 삭제
      - KAFKA_CFG_COMPRESSION_TYPE=snappy # Snappy 압축 사용

    ports:
      - "9092:9092"  # Kafka 외부 접속 포트
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge

volumes:
  kafka_data:
    driver: local
  db_data:
    driver: local